import os

SECRET_KEY = os.getenv('INMENU_CORE_SECRET_KEY', 'ReUazeXhPWbTLR9HAjBa9AtM9ppBw4XgaIjCP2KvVNeyv44Xiy0cZmQQB4k0')
ENCRYPT_ALGORITHM = os.getenv('INMENU_CORE_ENCRYPT_ALGORITHM', 'HS256')
LIFETIME_CODE = int(os.getenv('INMENU_CORE_LIFETIME_CODE', '3600'))
SEND_CODE_INTERVAL = int(os.getenv('INMENU_CORE_SEND_CODE_INTERVAL', '60'))
BASE_S3_DOMEN = os.getenv('INMENU_CORE_BASE_S3_DOMEN')
