INSERT INTO dish_main(name,
photo_link,
descrition,
menu_main_id,
menu_category_id,
measure_unit_id) VALUES
('borscht', 'borscht_photo', 'red soup', 1, 1, 1),
('pea soup', 'pea soup_photo', 'pea', 1, 1, 1),
('cabbage soup', 'cabbage_soup_photo', 'cabbage', 1, 1, 1),
('hodgepodge', 'hodgepodge_photo', 'three kinds of meat', 1, 1, 1),
('pickle', 'pickle_photo', 'pearl and pickle', 2, 1, 1),
('kharcho', 'kharcho_photo', 'tomat', 2, 1, 1),
('Puree soup', 'Puree_soup_photo', 'puree and vegetables', 2, 1, 1),
('puree', 'puree_photo', 'potatoes', 1, 2, 1),
('pasta', 'pasta_photo', 'just pasta', 1, 2, 1),
('buckwheat', 'buckwear_photo', 'just buckwheat', 1, 2, 1),
('rice', 'rice_photo', 'just rice', 1, 2, 1),
('pearl barley', 'pearl_barley_photo', 'just pearl', 2, 2, 1),
('spaghetti', 'spaghetti_photo', 'just spaghetti', 2, 2, 1),
('vegetables', 'vegetables_photo', 'cucumber, tomat, carrot', 2, 2, 1),
('dried fruit juice', 'dried fruit juice_photo', 'prunes, dry', 1, 3, 2),
('juice', 'juice_photo', 'apple', 1, 3, 2),
('berry juice', 'berry juice_photo', 'cherry, strawberry', 1, 3, 2),
('berry compote', 'berry compote_photo', 'black pot', 1, 3, 2),
('dried fruits compote', 'dried fruits compote_photo', 'apple', 2, 7, 2),
('jelly', 'jelly_photo', 'raspberry, apple, sugar', 2, 7, 2),
('water', 'water_photo', 'just water', 2, 7, 2),
('latte', 'latte_photo', 'milk, filter', 1, 4, 2),
('cappuccino', 'cappuccino_photo', 'milk is cold, filter', 1, 4, 2),
('mokko', 'mokko_photo', 'just_mokko', 2, 8, 2),
('black tea', 'black_tea_photo', 'raspberry', 1, 4, 2),
('black tea', 'black_tea_photo', 'cherry', 1, 4, 2),
('black tea', 'black_tea_photo', 'strawberry', 2, 8, 2),
('green tea', 'green_tea_photo', 'just_green_tea', 2, 8, 2);